### ISSUE TITLE
Example PDB produces error for IMGT numbering

### ISSUE THREAD

**Issue by serbulent-av** [haddocking/HADDOCK-antibody-antigen#10]
The numbering script produces error with the example PDB file;

```
python ImmunoPDB.py -i 4G6K.pdb -o 4G6K_i.pdb --scheme i --fvonly --rename --splitscfv

4G6K.pdb could not be parsed: Cannot change id from `(' ', 10, ' ')` to `(' ', 11, ' ')`. The id `(' ', 11, ' ')` is already used for a sibling of this entity.
```

**Comment by amjjbonvin** [comment]
This is an issue related to the tool we use for the renumbering of the PDB which is called ANARCI and it is developed by the group of Charlotte Deane. 
Here is the link to the relative github repository: https://github.com/oxpig/ANARCI/blob/master/Example_scripts_and_sequences/ImmunoPDB.py

Unfortunately there is no much we can do about that. 
You could try to raise an issue in the ANARCI repository. 

Alternatively use our PDB tools to renumber the antibody, but then carefully check the numbering of the PDB file and of the predicted paratope to make sure they match.

We have several other antibody-antigen docking tutorial online which you might consult:

https://www.bonvinlab.org/education/HADDOCK24/HADDOCK24-antibody-antigen/

https://www.bonvinlab.org/education/HADDOCK3/HADDOCK3-antibody-antigen/

**Comment by rvhonorato** [comment]
Hi there @serbulent-av, thanks for reporting it.

I've just executed and it ran without producing errors;

```bash
$ conda activate haddock-antibody
(haddock-antibody) $ python ImmunoPDB.py -i 4G6K.pdb -o 4G6K_ch.pdb --scheme c --fvonly --rename --splitscfv
(haddock-antibody) $ head 4G6K_ch.pdb 
REMARK   6 SCHEME CHOTHIA
REMARK   6 ANARCI TYPE, PAIRING AND ASSIGNED GERMLINE DETAILS
REMARK   6 CHAIN H N_IG-V-DOMAINS 1
REMARK   6 CHAIN H DOMAIN 0 TYPE VH
REMARK   6 CHAIN H DOMAIN 0 PAIREDWITH CHAIN L DOMAIN 0
REMARK   6 CHAIN H DOMAIN 0 V_GENE_SPECIES mouse
REMARK   6 CHAIN H DOMAIN 0 V_GENE_GERMLINE IGHV8-12*01
REMARK   6 CHAIN H DOMAIN 0 V_GENE_GERMLINE_IDENTITY 0.82
REMARK   6 CHAIN H DOMAIN 0 J_GENE_SPECIES mouse
REMARK   6 CHAIN H DOMAIN 0 J_GENE_GERMLINE IGHJ3*01
```

Could you please share the output of `pip freeze` in the python environment you are trying to execute the script?

**Comment by rvhonorato** [comment]
Did some more investigation and it seems that the version of ImmunoPDB we are re-distributing cannot handle a few formats:

- martin ✅ 
- chotia ✅ 
- imgt ❌
- kabat ✅ 
- aho ❌
- wolguy ❌

I'll add this information to the main README.
