### ISSUE TITLE
Modify `ImmunoPDB.py` to only allow Chotia naming scheme 

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/HADDOCK-antibody-antigen#12]
As it has been noted by some users (#7, #10) not all naming schemes are allowed (https://github.com/haddocking/HADDOCK-antibody-antigen/pull/11/commits/e7487337dad38b0dad8e0acafd54392aaac0fde0). 

We should disable the options in the re-destributed `ImmunoPDB.py` script to only allow for Chotia naming scheme.

**Comment by Francesco03** [comment]
Please accept the pull request @rvhonorato
