### ISSUE TITLE
making antibody-antigen pipeline haddock-local friendly

### ISSUE THREAD

**Issue by antonkulaga** [haddocking/HADDOCK-antibody-antigen#5]
So far, the haddock-antibody-antigen pipeline does not generate all the files required for haddock-local run, in particular: ambig and unambig files, as well as passive residue list as well as run.param, are not generated.
I solved this issue in my antibody-antigen docker container which I published as a separate repository https://github.com/antonkulaga/haddock-antibody-docker . It needs some polishing but it kind of works. 
In this issue I want to know your opinion whether you think it is good to back-port tbl files and run.param generation to haddock-antibody-antigen repository or it is better just to reference my container in readme, so people who want to use local version will know that they can save some time by using my code or maybe you will suggest something totally different.

**Comment by Francesco03** [comment]
In my opinion I would keep the two repositories separated.

**Comment by amjjbonvin** [comment]
Yes this is what we previously already decided

**Comment by antonkulaga** [comment]
My other question was if it is worth to at least reference this container in readme so people will know they can use it with lical version of haddock?

**Comment by amjjbonvin** [comment]
We could add indeed a note somewhere - but it means you will have to provide support if any question comes up
