### ISSUE TITLE
IMGT annotation

### ISSUE THREAD

**Issue by yangche7** [haddocking/HADDOCK-antibody-antigen#7]
Hello, 
Thanks for putting up this great tool to annotate the Ab pdb. 

I just try to annotate the Ab structure with IMGT format, and it seems there is a small bag there as I got the error as shown below: 

**python ImmunoPDB.py -i test.pdb -o test2.pdb -s IMGT --fvonly --rename --splitscfv
--> test.pdb could not be parsed: Cannot change id from `(' ', 10, ' ')` to `(' ', 11, ' ')`. The id `(' ', 11, ' ')` is already used for a sibling of this entity**

And rest of the annotation format works just fine :) 
Will it be nice if IGMT format could work as well !
Thanks 
Best, 
Che

**Comment by amjjbonvin** [comment]
Thanks for your comment Che.

ImmunoPDB.py  is actually a script coming from ANARCI a tool developed by Charlotte Deane: [oxpig/ANARCI: Antibody Numbering and Antigen Receptor ClassIfication (github.com)](https://github.com/oxpig/ANARCI)

I suggest to check if the script from ANARCI is working fine. We can then update it on our side. If not working, then raise an issue in the ANARCI GitHub site

**Comment by rvhonorato** [comment]
@yangche7 thanks for reporting this issue, as @amjjbonvin mentioned above, this script is coming from the [Oxford Protein Informatics Group](https://github.com/oxpig/ANARCI). 

Unfortunately I could not find this particular script in any of their repositories so I suggest you contact them via [e-mail](http://opig.stats.ox.ac.uk/webapps/newsabdab/sabpred/about/#contact).
